[package]
name = "tcp"
version = "0.1.0"
authors = ["DonghyungKo <koko8624@gmail.com>"]
edition = "2018"

[lib]
name = "tcp"
path = 'src/lib.rs'
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
